# Generated by Django 5.2.7 on 2025-10-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('child', 'Детский'), ('adult', 'Взрослый'), ('family', 'Семейный'), ('student', 'Студенческий'), ('other', 'Другое')], max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('validity_duration', models.IntegerField(default=1, verbose_name='Срок действия (дни)')),
            ],
            options={
                'verbose_name': 'Тип билета',
                'verbose_name_plural': 'Типы билетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(choices=[('operator', 'Оператор'), ('administrator', 'Администратор')], max_length=50, verbose_name='Должность')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=13, unique=True, verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['surname', 'name'],
                'indexes': [models.Index(fields=['position'], name='first_app_s_positio_0c4512_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('min_height', models.IntegerField(choices=[(90, '90 см'), (120, '120 см'), (150, '150 см'), (155, '155 см'), (165, '165 см')], verbose_name='Минимальный рост (см)')),
                ('max_height', models.IntegerField(choices=[(120, '120 см'), (190, '190 см'), (165, '165 см')], verbose_name='Максимальный рост (см)')),
                ('min_age', models.IntegerField(choices=[(3, '3 года'), (6, '6 лет'), (14, '14 лет'), (16, '16 лет'), (18, '18 лет')], verbose_name='Минимальный возраст')),
                ('activity_status', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('capacity', models.IntegerField(choices=[(10, '10 человек'), (15, '15 человек'), (20, '20 человек')], verbose_name='Вместимость (чел)')),
                ('duration_minutes', models.IntegerField(choices=[(3, '3 минуты'), (6, '6 минут'), (10, '10 минут'), (8, '8 минут'), (15, '15 минут')], default=5, verbose_name='Продолжительность (мин)')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.staff', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Аттракцион',
                'verbose_name_plural': 'Аттракционы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='e-mail')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['surname', 'name'],
                'indexes': [models.Index(fields=['surname'], name='first_app_u_surname_097e53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('usage_time', models.DateTimeField(blank=True, null=True, verbose_name='Время использования')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.tickettypes', verbose_name='Тип билета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='SituationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='Фактическая продолжительность (сек)')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('delayed', 'Задержано')], default='pending', max_length=20, verbose_name='Статус')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.attractions', verbose_name='Аттракцион')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.staff', verbose_name='Сотрудник')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.tickets', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Сеанс аттракциона',
                'verbose_name_plural': 'Сеансы аттракционов',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['attraction', 'start_time'], name='first_app_s_attract_70e0a0_idx'), models.Index(fields=['status'], name='first_app_s_status_7feae9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['user', 'ticket_type'], name='first_app_t_user_id_da52cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['valid_until'], name='first_app_t_valid_u_81ed03_idx'),
        ),
    ]
