# Generated by Django 5.2.6 on 2025-10-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('min_height', models.IntegerField(choices=[(90, '90 см'), (100, '100 см'), (110, '110 см'), (120, '120 см'), (130, '130 см'), (140, '140 см'), (150, '150 см')], verbose_name='Минимальный рост (см)')),
                ('max_height', models.IntegerField(choices=[(140, '140 см'), (150, '150 см'), (160, '160 см'), (170, '170 см'), (180, '180 см'), (190, '190 см'), (200, '200 см')], verbose_name='Максимальный рост (см)')),
                ('min_age', models.IntegerField(choices=[(3, '3 года'), (6, '6 лет'), (8, '8 лет'), (10, '10 лет'), (12, '12 лет'), (14, '14 лет'), (16, '16 лет'), (18, '18 лет')], verbose_name='Минимальный возраст')),
                ('activity_status', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('capacity', models.IntegerField(choices=[(1, '1 человек'), (2, '2 человека'), (4, '4 человека'), (6, '6 человек'), (8, '8 человек'), (10, '10 человек'), (15, '15 человек'), (20, '20 человек')], verbose_name='Вместимость (чел)')),
                ('duration_seconds', models.IntegerField(choices=[(60, '1 минута'), (120, '2 минуты'), (180, '3 минуты'), (240, '4 минуты'), (300, '5 минут'), (420, '7 минут'), (600, '10 минут'), (900, '15 минут')], verbose_name='Продолжительность (сек)')),
            ],
            options={
                'verbose_name': 'Аттракцион',
                'verbose_name_plural': 'Аттракционы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('operator', 'Оператор'), ('administrator', 'Администратор'), ('manager', 'Менеджер'), ('technician', 'Техник')], max_length=50, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('child', 'Детский'), ('adult', 'Взрослый'), ('family', 'Семейный'), ('student', 'Студенческий'), ('vip', 'VIP'), ('season', 'Сезонный'), ('other', 'Другое')], max_length=80, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('validity_duration', models.IntegerField(default=1, verbose_name='Срок действия (дни)')),
            ],
            options={
                'verbose_name': 'Тип билета',
                'verbose_name_plural': 'Типы билетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=15, unique=True, verbose_name='Паспорт')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='e-mail')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Пароль')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name'], name='first_app_u_last_na_bd02a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.tickettypes', verbose_name='Тип билета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='SituationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='Фактическая продолжительность (сек)')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('delayed', 'Задержано')], default='pending', max_length=20, verbose_name='Статус')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.attractions', verbose_name='Аттракцион')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.staff', verbose_name='Сотрудник')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.tickets', verbose_name='Билет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сеанс аттракциона',
                'verbose_name_plural': 'Сеансы аттракционов',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['user', 'ticket_type'], name='first_app_t_user_id_da52cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tickets',
            index=models.Index(fields=['valid_until'], name='first_app_t_valid_u_81ed03_idx'),
        ),
        migrations.AddIndex(
            model_name='situationstage',
            index=models.Index(fields=['attraction', 'start_time'], name='first_app_s_attract_70e0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='situationstage',
            index=models.Index(fields=['status'], name='first_app_s_status_7feae9_idx'),
        ),
    ]
