# Generated by Django 5.2.7 on 2025-10-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='duration_minutes',
            field=models.IntegerField(null=True, verbose_name='Продолжительность (мин)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='max_height',
            field=models.IntegerField(null=True, verbose_name='Максимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='min_age',
            field=models.IntegerField(null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='min_height',
            field=models.IntegerField(null=True, verbose_name='Минимальный рост (см)'),
        ),
    ]
