# Generated by Django 5.2.6 on 2025-10-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationstage',
            name='user',
        ),
    ]
