# Generated by Django 5.2.7 on 2025-10-25 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_attractions_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='attraction_images/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Фотография сотрудника'),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время покупки'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.tickettypes', verbose_name='Тип билета'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Действителен до, null=True, blank=True'),
        ),
    ]
