# Generated by Django 5.2.7 on 2025-10-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_attractions_main_image_staff_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='capacity',
            new_name='sourceity',
        ),
    ]
